[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
cmds = [
  "chmod +x mvnw",
  "./mvnw clean package -DskipTests -Dfile.encoding=UTF-8"
]

[start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -Dfile.encoding=UTF-8 -jar target/vitalexa-backend.jar"
